<?php

namespace App\Support\Hyper;

/**
 * The texts of the Hyperbitcoinization match page's script (plan "Hyperbitcoinization", P2): English keys, as
 * resources/js/hyper/*.js write them (t(), T(), tr()), translated here through __() and lang/de.json and handed
 * to the page as one dictionary. The page shows a key without an entry as it is.
 *
 * tests/Feature/Hyper/HyperTextsTest.php keeps KEYS equal to the keys the scripts use and every key in
 * lang/de.json, so a text added to the game is never English on the German page.
 */
final class HyperTexts
{
    /** @var list<string> */
    public const array KEYS = [
        'Brrrr zone: the Fed prints more',
        'Frankfurt: Lagarde only sees charts',
        'London fog: interest in the endless rain',
        'Safecrackers wanted: bank secrecy against HODL',
        'Winter is coming. So is inflation.',
        'Behind the great firewall',
        'Zero interest under cherry blossoms',
        'Savannah of growth',
        'Volcano bonds: mining with lava',
        'Down Under: fiat stands on its head',
        'Mining hub: the hashrate is boiling',
        'SEED? GONE.',
        'OUCH',
        '10,000 BTC',
        'LOOKS PROFESSIONAL',
        'Trade war',
        'Brexit reloaded',
        'Gas summit',
        'Neighbours’ quarrel',
        'Fed against volcano',
        'Transatlantic rate dispute',
        'Special relationship, cancelled',
        'Colonial repayment',
        'Iron ore poker',
        'Boundless friendship ends',
        'Bank secrecy under fire',
        'Silk Road debt',
        'Cold rate war',
        'ECB · FRANKFURT',
        'SNB · VAULT',
        'PBOC · BEIJING',
        'BOJ · TOKYO',
        'RATE 0.00 %',
        'AFRICAN CENTRAL BANK',
        'Someone',
        'Public on Nostr, signed with your key.',
        'Log in to write in the table chat.',
        ':count votes',
        'Closed: the match is over.',
        'Match voided',
        'The league voided this tournament match. It counts nowhere and is not rated.',
        'Log in to vote.',
        'One vote per account, public on Nostr. Spectators only.',
        'The vote did not reach any relay. Please try again.',
        'Quoted message',
        ':emoji, :count',
        'React',
        'No messages yet. Say hello to the table.',
        'Connecting to the chat …',
        'No Nostr signer found. Install a Nostr browser extension or use a remote signer.',
        'The message did not reach any relay. Please try again.',
        'Keep it to :max characters.',
        'One message every 2 seconds. Try again in a moment.',
        'Dollar Zone',
        '+25 % fiat income',
        'South American Union',
        '+2 fiat per turn',
        '10 % interest instead of inflation',
        'Euro Bloc',
        'ECB',
        'Plebs 20 % cheaper',
        'Vault: always +1 defence',
        'Rouble Fortress',
        '+1 defence in the whole space',
        'Yuan Sphere',
        'Every 3rd pleb free',
        'Your fiat does not decay',
        'Afro Union',
        'African Central Bank',
        '+2 free plebs per turn',
        'Australia & Oceania',
        'Canada',
        'West Coast',
        'Mexico',
        'Colombia',
        'Argentina',
        'Iceland',
        'Ireland',
        'Scandinavia',
        'Western Europe',
        'Eastern Europe',
        'Mediterranean',
        'Zurich',
        'Moscow',
        'West Siberia',
        'Yakutia',
        'Far East',
        'Kazakhstan',
        'Central Asia',
        'Mongolia',
        'Manchuria',
        'Beijing',
        'India',
        'Tokyo',
        'Cairo',
        'Libya',
        'Arabia',
        'Persia',
        'West Africa',
        'Horn of Africa',
        'East Africa',
        'Congo',
        'Zambezi',
        'South Africa',
        'Indonesia',
        'New Zealand',
        'PACIFIC OCEAN',
        'ATLANTIC OCEAN',
        'INDIAN OCEAN',
        'SOUTHERN OCEAN',
        'ARCTIC OCEAN',
        'TOPPLED',
        'HYPERBITCOINIZATION',
        'Fiat is history.',
        'The printing press runs hot. Forever.',
        'ECB Bot',
        'Europe is now a form in triplicate.',
        'GOLD WINS',
        'TOLD YOU SO',
        'Gold for 5000 years. And now here too.',
        'WEN LAMBO? NOW!',
        'New token, new luck. The chart points up. For now.',
        'BITCOIN IS DEAD',
        'For the 475th time. This time for real.',
        'Money Printer',
        '+8 free plebs. Next round everyone pays 50 % more per pleb.',
        'Jerome ordered new ink.',
        '51% Attack',
        'Take a neighbouring territory with at most 3 units without rolling.',
        'Enough hashrate for new rules.',
        'The richest opponent loses 30 % of their sats.',
        'The seed was in the recycling.',
        'One of your territories defends with +1 until your next turn.',
        'Nobody sells here.',
        'El Salvador Move',
        'Coin flip: your sats +25 % or −25 %.',
        'Do not look at the app.',
        'An enemy central bank loses 2 units.',
        'Governor and gold now in Dubai.',
        'Pizza Day',
        'You lose 10 % of your sats but get 3 free plebs.',
        '10,000 BTC for two pizzas. Delicious.',
        'Lagarde’s Crystal Ball',
        '+3 fiat and a look at the next card.',
        'Looks professional.',
        'Plebs cost half this turn.',
        'Everything on sale.',
        'An enemy territory with exactly 1 unit turns neutral.',
        'The cleaner was thorough.',
        'Recruit',
        'Fiat comes from territories and central banks. Buy plebs and place them. Leftover fiat is eaten by inflation.',
        'Attack',
        'Tap a glowing territory, then a pulsing neighbour. You see the odds before the roll.',
        'Fortify',
        'Move troops once per turn into a neighbouring territory of yours, then end the turn.',
        'How to win',
        'Knock everyone out, or hold the most central banks at the round limit. Sats are loot: they buy maxis and ASICs and are credited to you.',
        ':name: :emote',
        'Not so fast. Stickers again in :seconds s.',
        'One clip per turn. The next in :seconds s or next turn.',
        'The server did not answer. Please try again.',
        'neutral',
        ':name (bot)',
        'Odds from :name',
        ':count plebs',
        ':count maxi',
        ':count ASIC',
        'Mining',
        'Held by',
        'Troops',
        'Defence bonus',
        'Space complete',
        'no',
        'Space bonus',
        ':sats sats/turn',
        'Attack dice',
        'ASIC rig: highest die',
        'ASIC cracks the central bank',
        'Bank +0',
        'No ASIC rig along',
        'Defence dice',
        'Central bank (:bank)',
        'Bitcoin maxi: HODL',
        'Swiss vault',
        ':zone complete',
        'A tie wins',
        'Defence',
        'ATTACK',
        'DEFENCE',
        'ASIC +1 on the highest die',
        'Offence',
        '+:bonus on the highest die',
        'no bonus',
        ':name attacks you',
        'Battle for',
        ':pct % chance to win',
        'Move troops in',
        'Move troops',
        'From :from to :to. One unit always stays behind.',
        'Event card',
        ':name: +:fiat fiat, +:sats M sats',
        'Your turn',
        '+:fiat fiat · +:sats M sats',
        'is on the move',
        ':name conquers :territory.',
        ':name topples the :bank.',
        'Central bank toppled',
        ':bank · +1 M sats',
        ':name holds all of :zone.',
        'Orange pill',
        ':zone complete · +:sats sats per turn',
        ':name moves :count units to :territory.',
        ':name collects interest in London.',
        'Inflation',
        '−:fiat fiat gone up in smoke',
        ':name is out.',
        'You are out',
        ':name is out',
        'One fiat faction fewer',
        'The money printer kicks in: plebs cost 50 % more.',
        'Your turn ran out.',
        '+8 free plebs · inflation next round',
        ':territory taken over',
        ':name loses :sats M sats',
        ':territory holds with +1',
        'Price +25 %. To the moon!',
        'Price −25 %. Ouch.',
        ':territory plundered',
        'Next card: :card',
        ':territory turns neutral',
        ':name plays :card: :effect',
        'You made the :name happen!',
        'You win as :side!',
        ':name wins',
        'Round limit: :banks central banks, :territories territories',
        'Everyone else is out',
        'round :round',
        ':sats M sats loot, credited to you',
        'The most central banks',
        'The page is out of date. Please reload it.',
        ':name is on the move.',
        'That target does not fit the card.',
        'Place troops on your own glowing territories.',
        'Not enough fiat. On to the attack.',
        'Not enough sats.',
        'An attack needs at least 2 units next to an enemy.',
        'Pick your attacking territory first (glowing).',
        'Attack neighbours only. Dashed lines are sea routes.',
        'Already moved this turn. End your turn.',
        'Only 1 unit there.',
        'Only into a neighbouring territory of yours.',
        'Match over.',
        'You are watching. :name is on the move.',
        ':name is on the move …',
        ':card: tap a glowing target. Tap the card again to cancel.',
        'Place :count free plebs on your glowing territories.',
        'Pick a unit, then tap your glowing territories.',
        'Attack from :name: tap a pulsing target.',
        'Tap a glowing territory as the attacker.',
        'Moved. Now end your turn.',
        'Tap a pulsing neighbouring territory of yours.',
        'Move once: tap the start, then the target.',
        'Chronicle',
        'Round :round',
        'Inflation!',
        ':cost fiat',
        ':count free plebs to place',
        'Match over',
        ':name moves',
        'To the attack',
        'End attack',
        'End turn',
        'at the table',
        'away',
        ':count terr.',
        '1 bank',
        ':count banks',
        '1 card',
        ':count cards',
        'Currency spaces',
        'Map view (key M)',
        'Spaces',
        'Owners',
        ':zone: taking it all brings :sats M sats per turn',
        'M sats',
        'Move troops into the conquered territory first.',
        'You play cards in your own turn.',
        'Time left for :name',
        'Place the free plebs first.',
        'Cinematics on',
        'Cinematics off: battles and cards run fast',
        'Effects on',
        'Effects off (dice, clicks, explosions)',
        'Soundboard clips on',
        'Soundboard clips off, effects stay',
        'Really leave? A bot takes over.',
        'You left. A bot plays your seat now.',
        'The Hyperbitcoinization begins. Fiat rots, sats stay.',
        'Effects',
        'Soundboard',
        'Music',
        'Muted: :what. Switch them on again at the top right.',
        'Connection lost. Reconnecting …',
        // P3: rematch and replay.
        'Rematch asked',
        'Accept the rematch',
        'Waiting for :names',
        // P6: a rematch declined or run out.
        'Rematch',
        'The rematch started.',
        ':name declined the rematch.',
        'The rematch offer has run out.',
        'Open until :time.',
        'Pause',
        'Again',
        'Play',
        // P3b: the end-of-match statistics.
        ':name wins in round :round',
        'First central bank toppled',
        ':name takes :territory from :loser',
        ':name takes :territory',
        'A whole currency space',
        ':name holds the whole :zone',
        'Comeback from the last region',
        ':name was down to :zone in round :round and still won',
        'Perfect dice',
        'Three sixes for :name on :territory',
        'Knockout',
        ':name knocks :loser out of the game',
        ':name, the richest, loses :sats M sats',
        'Coin flip lost',
        ':name bets on El Salvador: −25 %',
        ':name pays for pizza in sats',
        ':name seizes :territory',
        'Territories',
        'Units',
        'Central banks',
        'Fiat',
        'Sats collected',
        'Charts',
        'Leaders',
        'Moments (:count)',
        'Chart',
        'Turning points',
        'Round :round: :loser loses :territory',
        'Round :round: :name takes the whole :zone',
        'Round :round: :name knocks out :loser',
        ':metric per player over :rounds rounds',
        'Nobody',
        'Most battles',
        ':count battles',
        'Biggest conquest run',
        ':count territories in one turn',
        'Longest defence',
        ':territory held against :count attacks',
        'Most loot',
        ':sats M sats',
        'Unluckiest roller',
        ':pips pips against the odds',
        ':count dice',
        'Pride moment',
        'Meme moment',
        // Team matches (P4): team chat, clan sides, team pages and the pacing's buttons.
        'Team :number',
        'Tap to continue',
        'Tap to skip',
        'Your team wins!',
        ':clan wins',
        'Team chat',
        'Table chat',
        'Private, encrypted for your team',
        'Public on Nostr',
        'MVP: :name with :count conquests',
        'First central bank for :clan',
        ':clan holds a whole currency space',
        'The whole :zone, together',
        ':clan knocks out a rival',
        ':name throws :loser of :rival out of the game',
        'Skip all',
        'Done',
        'Next step',
        'Teams',
        'Meetup · :city',
        'Meetup',
        'Clan',
        'Bots',
        'Winner',
        'MVP',
        'Conquests',
        'Loot',
        'vs',
        'Clan pride',
        'Only your team reads this. Plan your next move.',
        'Only your team reads this chat.',
        'The team chat is off here: no chat relay is set up.',
        'Your signer cannot encrypt (NIP-44), so the team chat stays closed.',
        'Private: sealed for :names.',
        'Your teammates are bots: nobody else reads this.',
    ];

    /**
     * Every key with its text in the current language.
     *
     * @return array<string, string>
     */
    public static function dictionary(): array
    {
        $texts = [];

        foreach (self::KEYS as $key) {
            $text = __($key);
            $texts[$key] = is_string($text) ? $text : $key;
        }

        return $texts;
    }
}
