<?php

use App\Support\Board\CheckersRules;
use App\Support\Board\NineMensMorrisRules;

/*
 * Replays the Mühle and Dame games of the campaign through the app's own rules
 * (app/Support/Board/*Rules.php) and writes lib/boardgames.data.js. Every move
 * must be in the rules' legalMoves() of its position, or nothing is written:
 * no board position in the campaign is typed by hand.
 * Usage: php docs/promo/src/gen-boardgames.php [rules dir]
 * The games were found by a greedy self-play (longest capture / mill first),
 * then fixed here as move lists.
 */
$dir = rtrim($argv[1] ?? __DIR__.'/../../../app/Support/Board', '/');
foreach (['BoardRules', 'NineMensMorrisRules', 'CheckersRules'] as $class) {
    require $dir.'/'.$class.'.php';
}

const GAMES = [
    'morris' => ['rules' => NineMensMorrisRules::class, 'moves' => 'd3 e5 a4 c3 e3 b4 g7 f6 d6 a7 e4 d1 a1 d7 d2 c4 g4 c5xg4 g7-g4 d7-g7 e4-f4 b4-b2 e3-e4xg7 c5-d5 f4-f2 c4-c5xa4 f2-f4xf6 c3-c4 a1-a4 b2-b4 g4-g1 c4-c3 g1-g4xc3 a7-d7 g4-g1 b4-b6 g1-g4xd7 b6-b4 d6-f6 b4-b6 d2-f2xb6 c5-c4 d3-c3 c4-c5xa4 g4-g7 c5-c4 g7-g4xe5 d5-b4 f2-d2 d1-a4xc3 d2-f2xc4'],
    'checkers' => ['rules' => CheckersRules::class, 'moves' => 'c3-d4 b6-c5 d4xb6 a7xc5 e3-d4 c5xe3 d2xf4 d6-c5 f2-e3 f6-e5 f4xd6xb4 b8-a7 g3-f4 a7-b6 e1-d2 e7-d6 f4-e5 d6xf4 e3xg5 h6xf4 b4-a5 c7-d6 a5xc7xe5xg3 g7-f6 d2-e3 h8-g7 g1-f2 f6-e5 g3-f4 e5xg3xe1 e3-d4 e1-c3 h2-g3 c3xe5xh2 b2-c3 h2-c7 a1-b2 c7-d6 c1-d2 d6-c7 c3-d4 c7-h2 d4-e5 h2xd6 a3-b4 d6xa3xc1xe3'],
];

$out = [];
foreach (GAMES as $id => $game) {
    $rules = new $game['rules'];
    $position = $rules->start();
    $history = [$rules->serialize($position)];
    $plies = [['pos' => $history[0], 'move' => null, 'path' => []]];
    foreach (explode(' ', $game['moves']) as $n => $move) {
        if (! in_array($move, $rules->legalMoves($position), true)) {
            fwrite(STDERR, "FAIL {$id} ply {$n}: {$move} is not legal\n");
            exit(1);
        }
        $position = $rules->apply($position, $move);
        $history[] = $rules->serialize($position);
        $plies[] = ['pos' => end($history), 'move' => $move, 'path' => $rules->path($move)];
    }
    $out[$id] = ['plies' => $plies, 'outcome' => $rules->outcome($position, $history)];
    echo "{$id}: ".(count($plies) - 1).' plies, '.json_encode($out[$id]['outcome'])."\n";
}

file_put_contents(__DIR__.'/lib/boardgames.data.js', "/* Generated by gen-boardgames.php from the app's own rules. Do not edit. */\nwindow.BG_DATA = ".json_encode($out, JSON_UNESCAPED_SLASHES).";\n");
