<?php

use App\Support\Rating\ClanRating;
use App\Support\Rating\EloRating;
use App\Support\Rating\GlobalRating;
use App\Support\Rating\NipMath;
use App\Support\Rating\RankTiers;

/**
 * The rating examples of the Pre-Season sample ledger (generated by
 * tests/Fixtures/SeasonChain/export_ledger.py).
 *
 * @return array<string, mixed>
 */
function ratingLedger(): array
{
    static $rating = null;

    return $rating ??= json_decode((string) file_get_contents(__DIR__.'/../../Fixtures/SeasonChain/pre-season-ledger.json'), true, flags: JSON_THROW_ON_ERROR)['rating'];
}

/** @return array<string, int> */
function ratingTiers(): array
{
    return (require __DIR__.'/../../../config/season.php')['tiers'];
}

test('rounding is half away from zero, symmetric as the NIP requires', function () {
    expect([NipMath::round(0.5), NipMath::round(-0.5), NipMath::round(-15.5), NipMath::round(2.4999)])->toBe([1, -1, -16, 2]);
});

test('the inverse normal distribution matches Python\'s NormalDist().inv_cdf bit for bit', function (float $p, float $x) {
    expect(NipMath::inverseNormal($p))->toBe($x);
})->with([
    [0.001, -3.090232306167813],
    [0.02, -2.0537489106318225],
    [0.5, 0.0],
    [0.575, 0.18911842627279238],
    [0.87, 1.1263911290388005],
    [0.99, 2.3263478740408408],
    [1e-12, -7.034483825301132],
]);

test('Elo replays every rated result of the ledger, with the provisional k-factor', function () {
    $ledger = ratingLedger();
    $elo = new EloRating(1000, $ledger['k'], $ledger['provisional_k'], $ledger['provisional']);

    foreach (['daily', 'series'] as $ladder) {
        $ratings = [];
        $results = [];
        foreach ($ledger[$ladder] as $result) {
            [$c, $d] = [$result['challenger'], $result['challenged']];
            $rated = $elo->rate($ratings[$c] ?? 1000, $ratings[$d] ?? 1000, $result['score'], $results[$c] ?? 0, $results[$d] ?? 0);

            expect([[$ratings[$c] ?? 1000, $rated['challenger']], [$ratings[$d] ?? 1000, $rated['challenged']]])
                ->toBe([$result['challenger_elo'], $result['challenged_elo']]);

            [$ratings[$c], $ratings[$d]] = [$rated['challenger'], $rated['challenged']];
            $results[$c] = ($results[$c] ?? 0) + 1;
            $results[$d] = ($results[$d] ?? 0) + 1;
        }
    }

    expect(count($ledger['daily']) + count($ledger['series']))->toBe(99);
});

test('a provisional side moves with k 40, an established one with k 32, so the pairing is not zero-sum', function () {
    $rated = (new EloRating)->rate(1000, 1000, 1.0, 0, 5);

    expect($rated)->toBe(['challenger' => 1020, 'challenged' => 984, 'challenger_delta' => 20, 'challenged_delta' => -16]);
});

test('rank tiers: 21 tokens from config, provisional below five results', function () {
    $tiers = new RankTiers(ratingTiers(), ratingLedger()['provisional']);

    $actual = array_map(fn (array $row): string => $tiers->tierFor($row['elo'], $row['games']), ratingLedger()['tiers']);

    expect($actual)->toBe(array_column(ratingLedger()['tiers'], 'tier'))
        ->and(ratingTiers())->toHaveCount(21)
        ->and([$tiers->tierFor(899, 5), $tiers->tierFor(900, 5), $tiers->tierFor(1000, 5), $tiers->tierFor(1424, 9), $tiers->tierFor(1425, 9), $tiers->tierFor(2000, 4)])
        ->toBe(['bronze-1', 'bronze-2', 'silver-3', 'grand-champion-2', 'grand-champion-3', 'provisional']);
});

test('Global Rating reproduces the ledger and the NIP example', function () {
    $ledger = ratingLedger();
    $global = new GlobalRating(5);

    $actual = array_map(fn (array $player): ?int => $global->compute(array_map(fn (array $entry): array => [
        'weight' => $entry['weight'], 'rating' => $entry['rating'], 'ladder' => $ledger['ladders'][$entry['ladder']],
    ], $player['entries'])), $ledger['global_rating']);

    expect($actual)->toBe(array_column($ledger['global_rating'], 'expected'))
        ->and(array_filter($actual))->not->toBeEmpty()
        // NIP "Global Rating": alice 4 blitz results at p = 0.9, one series at p = 0.75 -> 1225.
        ->and($global->compute([
            ['weight' => 4, 'rating' => 1028, 'ladder' => [1028, 1010, 1000, 990, 980]],
            ['weight' => 1, 'rating' => 1016, 'ladder' => [1016, 984]],
        ]))->toBe(1225)
        ->and($global->compute([['weight' => 4, 'rating' => 1028, 'ladder' => [1028, 1000]]]))->toBeNull();
});

test('clan rating is the top-three average, hashrate adds points and team-win bonuses', function () {
    $ledger = ratingLedger();
    [$win, $draw, $loss, $bonus] = $ledger['hashrate']['points'];
    $clans = new ClanRating(3, $win, $draw, $loss, $bonus);

    expect(array_map(fn (array $clan): ?int => $clans->rating($clan['elos']), $ledger['clan_rating']))
        ->toBe(array_column($ledger['clan_rating'], 'expected'))
        ->and(array_map(fn (array $clan): int => $clans->hashrate($clan['wins'], $clan['draws'], $clan['losses'], $clan['team_wins']), $ledger['hashrate']['clans']))
        ->toBe(array_column($ledger['hashrate']['clans'], 'expected'))
        ->and($clans->rating([1100, 1000]))->toBeNull();
});
